Add meta/main.yml
jtyr/ansible-rpmbuild pull request #1
Opened 2017-03-11 07:26 UTC by cognifloyd

This makes installing via ansible-galaxy possible.

2017-03-12 21:18 UTC, jtyr requested changes

2017-03-12 21:18 UTC, jtyr commented on meta/main.yml
> +  - jtyr.config_encoder_filters
Please change this like to:

```
- config_encoder_filters
```

and follow [installation instructions](https://github.com/jtyr/ansible-config_encoder_filters#installation) to install the dependency.

2017-03-12 21:18 UTC, jtyr commented on meta/main.yml
> +  description: Ansible role creates RPM build environment
Please change this line to:

```
description: Ansible role which creates RPM build environment.
```

2017-03-12 21:18 UTC, jtyr commented on meta/main.yml
> +    - name: Fedora
Is it necessary to specify Fedora if all EL versions are covered?

2018-05-02 17:27 UTC, cognifloyd commented
So, I've returned to the project where I'm using rpmbuild after a year on other stuff :) I resolved the issues you mentioned.

2018-07-29 15:09 UTC, jtyr commented
This has been implemented.

2018-07-29 15:09 UTC, closed without merging